name: Bump version & Publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Select the package'
        required: true
        type: choice
        options:
          - 'core/cli'
          - 'core/create-pota'
          - 'scripts/webpack'
          - 'scripts/vite'
          - 'scripts/react-webpack'
          - 'scripts/react-vite'
          - 'scripts/muban-webpack'
          - 'scripts/plop'
          - 'templates/vanilla'
          - 'templates/react-base'
          - 'templates/react'
          - 'templates/next'
          - 'templates/muban'
      version:
        description: 'Semver type of new version'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
      prereleaseid:
        description: 'Prerelease id (rc)'
        required: false
        default: ''

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: bump version
        run: |
          cd ${{ github.event.inputs.package }}
          npm version ${{ github.event.inputs.version }} --no-git-tag-version --preid ${{ github.event.inputs.prereleaseid }}
          git add .
          git commit -m "${{ github.event.inputs.package }} v$(npm pkg get version | tr -d '"')"
          git tag $(npm pkg get name | tr -d '"')@$(npm pkg get version | tr -d '"') -m "${{ github.event.inputs.package }} v$(npm pkg get version | tr -d '"')"

      - name: publish
        run: |
          cd ${{ github.event.inputs.package }}
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push latest version
        run: git push origin main --follow-tags
